### ISSUE TITLE
MicroProfile dependency analysis fails since jQA 2.0

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [jqassistant-tutorials/jakarta-ee-dependencies#11]
The exisiting configuration for the MicroProfile 5 dependencies fails on jQA 2.0.1 with no result - that worked before the jQA Major Release.

The same happens for the MicroProfile 6 version:

`
        <repo.url>https://repo1.maven.org/maven2</repo.url>
        <repo.filter>org.eclipse.microprofile*:*:*</repo.filter>
        <platform.groupId>org.eclipse.microprofile</platform.groupId>
        <platform.artifactId>microprofile</platform.artifactId>
        <platform.type>pom</platform.type>
        <platform.version>6.0</platform.version>
`

**Comment by DirkMahler** [comment]
Duriing migration to jQA 2.0.x the concept for resolving artifact dependencies has been removed because the M2 repo scanner comes with a built-in mechanism. But it turned out, that there are differences in the way it is done (especially: the MP platform artifacts are of type "pom", not "jar" as the others). As an intermediary solution the according concept has been re-introduced to this project.

**Comment by JanWesterkamp-iJUG** [comment]
I tested all the component specs nearly now and all the runs with the former concept (before your fix) of type POM fail.

Another effect is, that all the specs with no downstream dependency at all show errors too - only the Specification Dependency Diagram is rendered, but i.e. the Platform Dependency Diagram or the CSV list are empty. This might have a differen cause of course.

Thanks a lot for the fix - I will try this and report results soon.

**Comment by JanWesterkamp-iJUG** [comment]
The POM issue is fixed now, except the minor issue when the spec has no dependencies.

I created a separate issue for this: #12
